name: Android CI and CD

on:
  push:
    branches:
      - main
      - qa
      - develop
  pull_request:
    branches:
      - main
      - qa

env:
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x android-demo-app/gradlew

      - name: Build with Gradle
        working-directory: android-demo-app
        run: ./gradlew build

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Date and Time
        id: date
        run: echo "::set-output name=current_date_time::$(date +'%d-%m-%Y-%H-%M-%S')"

      - name: Build and analyze with SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.sonartoken }}
          SONAR_HOST_URL: ${{ secrets.sonarhost }}
          CURRENT_DATE_TIME: ${{ steps.date.outputs.current_date_time }}
        run: |
          echo "Current date and time: $CURRENT_DATE_TIME"
          cd android-demo-app && ./gradlew build sonar --info

      - name: Copy APK files to a directory
        run: |
          mkdir -p /home/runner/work/android-CI/android-CI/apk-files/debug /home/runner/work/android-CI/android-CI/apk-files/release
          cp /home/runner/work/android-CI/android-CI/android-demo-app/app/build/outputs/apk/dev/debug/app-dev-debug.apk /home/runner/work/android-CI/android-CI/apk-files/debug/app-debug-${{ steps.date.outputs.current_date_time }}.apk
          cp /home/runner/work/android-CI/android-CI/android-demo-app/app/build/outputs/apk/dev/release/app-dev-release-unsigned.apk /home/runner/work/android-CI/android-CI/apk-files/release/app-release-unsigned-${{ steps.date.outputs.current_date_time }}.apk

      - name: Upload apk-files Directory
        uses: actions/upload-artifact@v3
        with:
          name: apk-files-artifacts
          path: ${{ github.workspace }}/apk-files/
          if-no-files-found: ignore

  notification:
    name: Notification to Teams
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Teams
        uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ secrets.CI_GITHUB_TOKEN }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.ref, 'refs/heads/qa') || contains(github.ref, 'refs/heads/main')
    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v2

      - name: Download apk-files-artifacts
        uses: actions/download-artifact@v3
        with:
          name: apk-files-artifacts
          path: ${{ github.workspace }}/apk-files/

      - name: Display structure of downloaded files of Artifact 
        run: ls -R
        working-directory: ${{ github.workspace }}/apk-files/

      - name: Public IP of Github Hosted Runner
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.JFROG_SG_ID }} --protocol tcp --port 8082 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest
        env:
          # JFrog platform url (for example: https://acme.jfrog.io) 
          JF_URL: https://acm.jfrog.io/artifactory/gradle-release/
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Create folder for qa and main branch in apk-files
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/qa' ]]; then
            cd /home/runner/work/android-CI/android-CI/apk-files && mkdir -p qa && mv debug/ qa/ && mv release/ qa/
          elif [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            cd /home/runner/work/android-CI/android-CI/apk-files && mkdir -p main && mv debug/ main/ && mv release/ main/
          fi

           name: Push Build to Artifactory

            on:
              push:
      
           jobs: 
            build:
             runs-on: ubuntu-latest
            steps:
      # This action checks out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # This action sets up the JFrog CLI with the Artifactory URL and access token     
      - uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      # This command adds a new server configuration to the JFrog CLI   
      - run: |
          export SERVER_ID="test"
          jf c add $SERVER_ID --url=$URL --access-token=$ACCESS_TOKEN --interactive=false

      # This action creates a new test file and uploads it to Artifactory   
      - name: Push Build to Artifactory
        run: |
          echo "test file " > test.txt
          export BUILD_NAME="my-build"
          export BUILD_MODULE="my-module"
          export BUILD_NUMBER="1"
          export PATH_TO_DIRECTORY="name/version/dates"
          jf rt upload "test.txt" example-repo-local/$PATH_TO_DIRECTORY --build-name $BUILD_NAME --build-number $BUILD_NUMBER --module $BUILD_MODULE

      # This action publishes the build information to Artifactory and deletes older builds
      - name: Build to Artifactory
        run: |
          jf rt build-publish $BUILD_NAME $BUILD_NUMBER
          jf rt bdi c --max-builds=1
