name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x android-demo-app/gradlew

      # Build with Gradle
      - name: Build with Gradle
        working-directory: android-demo-app   # Set the working directory to the Android project root
        run: ./gradlew build   # Execute the Gradle wrapper script to build the project

      # Additional steps for SonarQube analysis
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.sonartoken }}     # Use the secret named "sonartoken"
          SONAR_HOST_URL: ${{ secrets.sonarhost }}  # Use the secret named "sonarhost"
        run: cd android-demo-app && ./gradlew build sonar --info
