name: Android CI and CD

on:
  push:
    branches: 
      - main
      - qa
      - develop
  pull_request:
    branches:  
      - main
      - qa

env:
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x android-demo-app/gradlew

      - name: Build with Gradle
        working-directory: android-demo-app   
        run: ./gradlew build

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Date and Time
        id: date
        run: echo "::set-output name=current_date_time::$(date +'%d-%m-%Y-%H-%M-%S')"

      - name: Build and analyze with SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.sonartoken }}    
          SONAR_HOST_URL: ${{ secrets.sonarhost }} 
          CURRENT_DATE_TIME: ${{ steps.date.outputs.current_date_time }} 
        run: |
          echo "Current date and time: $CURRENT_DATE_TIME"
          cd android-demo-app && ./gradlew build sonar --info

      - name: Copy APK files to a directory
  run: |
     current_dir=$(pwd)
     mkdir -p apk-files/debug apk-files/release
     cp ${{ github.workspace }}/android-demo-app/app/build/outputs/apk/debug/app-debug.apk ${{ github.workspace }}/apk-files/debug/app-debug-${{ steps.date.outputs.current_date_time }}.apk
     cp ${{ github.workspace }}/android-demo-app/app/build/outputs/apk/release/app-release-unsigned.apk ${{ github.workspace }}/apk-files/release/app-release-unsigned-${{ steps.date.outputs.current_date_time }}.apk

  - name: Upload apk-files Directory
  uses: actions/upload-artifact@v3
  with:
    name: apk-files-artifacts
    path: ${{ github.workspace }}/apk-files/
    if-no-files-found: ignore
